### ISSUE TITLE
Upgrade Django 3.2

### ISSUE THREAD

**Issue by josircg** [larhud/timeline#29]
1) A data inicial e final ficaram com o texto "data inicial dt" 
2) A caixa do filtro ficou desposicionada. Pode aumentar um pouco mais a distância entre os campos de filtro (pode ser geral, direto no poweradmin)

![browse](https://user-images.githubusercontent.com/634507/234716532-964a39ef-d598-4903-9037-390bb0d27be0.png)

**Comment by fabiofsilva** [comment]
Manda o print de como é na versão anterior.


Enviado do Yahoo Mail para iPhone


Em quarta-feira, abril 26, 2023, 19:29, Josir Cardoso Gomes ***@***.***> escreveu:



   
   - A data inicial e final ficaram com o texto "data inicial dt"
   - A caixa do filtro ficou desposicionada. Pode aumentar um pouco mais a distância entre os campos de filtro (pode ser geral, direto no poweradmin)

**Comment by josircg** [comment]
Já entendi o problema da data. Falta só o posicionamento.

https://timeline.ibict.br/admin/base/noticia/

**Comment by fabiofsilva** [comment]
Tá a mesma coisa. Data inicial de Dt. Dt deve ser o nome do campo né? Qual o motivo de precisar do nome do campo ali?


Enviado do Yahoo Mail para iPhone


Em quarta-feira, abril 26, 2023, 20:10, Josir Cardoso Gomes ***@***.***> escreveu:




https://timeline.ibict.br/admin/base/noticia/

**Comment by josircg** [comment]
1) Faz assim: altera para ficar "Dt inicial" e "Dt final", ou seja, {{field label}} Inicial 

2) Vc conseguiu entender a questão da caixa do filtro?

**Comment by fabiofsilva** [comment]
https://bitbucket.org/josir/poweradmin/commits/f9f462af1f52262f9f41d66b35dab59c98d37ddf
Tem que reinstalar o poweradmin no servidor.

**Comment by josircg** [comment]
![tela](https://user-images.githubusercontent.com/634507/235239535-524bc892-3195-48df-bbec-26381b13ac71.png)

- O primeiro filtro tem que ficar na mesma linha do search
- O total de registros lidos ficou lá em cima - ele pode ser retirado.

**Comment by fabiofsilva** [comment]
Esse total faz parte de outro template…


Enviado do Yahoo Mail para iPhone


Em sexta-feira, abril 28, 2023, 20:21, Josir Cardoso Gomes ***@***.***> escreveu:





   
   - O primeiro filtro tem que ficar na mesma linha do search
   - O total de registros lidos ficou lá em cima - ele pode ser retirado.

**Comment by fabiofsilva** [comment]
https://bitbucket.org/josir/poweradmin/commits/03a7dcf84bb88aab004e4cc31c2ccc7df3f74dc5
Tem que reinstalar o poweradmin no servidor (talvez precise limpar o cache).
