### ISSUE TITLE
Melhoria na interface de busca

### ISSUE THREAD

**Issue by josircg** [larhud/timeline#43]
1) As fontes do header e dos campos estão muito grandes, podemos diminuir um ou 2 pontos.
2) Com isso, o botão de Pesquisa Avançada pode sumir e a página já entrar com todas as buscas habilitadas.
3) O cinza que delimita os campos está muito claro. Ele precisa ser + escuro
4) O campo de Veículo de Imprensa deve estar + perto do campo da data.
5) O botão "Listagem" tem que ser apenas um ícone e estar dentro campo Veículo de Imprensa. Escolha um icone que pareça com uma tabela. O ícone deve ter um hint "Listagem dos Veículos"
5) Novo botão com um ícone em formato de nuvem com o hint "Nuvem Temporal" apontando para /cronocloud

**Comment by ABTogawa** [comment]
Enviei modificações por e-mail
