### ISSUE TITLE
Novo layout para a página Timeline

### ISSUE THREAD

**Issue by josircg** [larhud/timeline#44]
Vamos refazer o cabeçalho e alguns botões da Timeline para ficar de acordo com o layout do email que eu enviei. 

Repare que esse formulário está no tema e não no projeto principal. O tema está aqui:

https://github.com/larhud/timeline-tema-covid

A única funcionalidade nova é o da Nuvem. Hoje o sistema mostra uma nuvem abaixo da timeline. Quando o usuário clicar o botão vamos substituir a timeline pela nuvem.

**Comment by josircg** [comment]
1) A busca por data parou de funcionar. Não sei se tem relação com o tema ou se já estava assim antes.

2) A visualização da nuvem tem que sofrer refresh quando o usuário alterar o mês/ano no combo. Igual já é feito na timeline.

**Comment by bonfimjustino7** [comment]
Itens ajustados, aguardando aprovação.
https://github.com/larhud/timeline-tema-covid/pull/12

**Comment by josircg** [comment]
Primeira versão já foi para produção. Aguardando os ajustes pedidos ao webdesigner.
